In [1]:
import os
import rootutils

from tqdm.notebook import tqdm

rootutils.setup_root(os.path.abspath('./'), indicator=".project-root", pythonpath=True, dotenv=True, cwd=True)

# auto-loading of imports from outside scripts
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

In [3]:
df_coord_numbs = pd.read_csv("data_cod/coord_numbs.csv")
df_coord_numbs.rename(columns={"smiles": "can_smiles"}, inplace=True)

In [4]:
# Drop rows and columns that contain only zeros:

rows_only_zeros = df_coord_numbs[(df_coord_numbs == 0).all(axis=1)]
columns_only_zeros = df_coord_numbs.loc[:, (df_coord_numbs == 0).all(axis=0)]

df_coord_numbs = df_coord_numbs.drop(columns=columns_only_zeros.columns, index=rows_only_zeros.index)

In [5]:
df_merged_temp = pd.read_csv("data_cod/cod_bradley_merged.csv")
df_merged_temp = df_merged_temp[df_merged_temp["id"].isin(df_coord_numbs["id"])]

# Only bradley, to use part of it for test:
df_bradley_temp = pd.read_csv("data_cod/bradley_with_cif.csv")
df_bradley_temp = df_bradley_temp[df_bradley_temp["id"].isin(df_coord_numbs["id"])]

---
## Creating Train and Test splits:
- 0.2 of Bradley is test, rest is train

In [6]:
TEST_BRADLEY_FRAC = 0.2

In [7]:
df_test = df_bradley_temp.sample(frac=TEST_BRADLEY_FRAC, random_state=42)

df_train = df_merged_temp.drop(index=df_merged_temp[df_merged_temp["id"].isin(df_test["id"])].index)

In [8]:
df_train = pd.merge(df_train, df_coord_numbs, on=["id", "can_smiles"], how="inner")
df_test = pd.merge(df_test, df_coord_numbs, on=["id", "can_smiles"], how="inner")

In [9]:
df_train

,id,can_smiles,T,cif_path,Ag–Ag,Al–H,H–Al,As–As,B–B,B–H,...,Se–Se,Si–H,H–Si,Si–Si,Sn–H,H–Sn,Sr–Sr,Ti–Ti,Zn–H,H–Zn
0,1000018,CC1(C)[C@@H]2CC[C@]3(C2)[C@H](O)CC[C@@H](O)[C@...,180.0,cifs/1000018.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1000019,CN(C)c1ccc(/C=C/C(=O)c2ccccc2O)cc1,-97.0,cifs/1000019.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1008189,OO,-40.0,cifs/1008189.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1008775,NC(N)=O,134.0,cifs/1008775.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1008776,NC(N)=O,134.0,cifs/1008776.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11852,9014479,ClCl,-101.0,cifs/9014479.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11853,9015081,c1ccc2c(c1)Cc1ccccc1-2,116.0,cifs/9015081.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11854,9015108,Cl,-114.2,cifs/9015108.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11855,9015583,ClCl,-101.0,cifs/9015583.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11856,9016437,Cl,-114.2,cifs/9016437.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df_train

,id,can_smiles,T,cif_path,Ag–Ag,Al–H,H–Al,As–As,B–B,B–H,...,Se–Se,Si–H,H–Si,Si–Si,Sn–H,H–Sn,Sr–Sr,Ti–Ti,Zn–H,H–Zn
0,1000018,CC1(C)[C@@H]2CC[C@]3(C2)[C@H](O)CC[C@@H](O)[C@...,180.0,cifs/1000018.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1000019,CN(C)c1ccc(/C=C/C(=O)c2ccccc2O)cc1,-97.0,cifs/1000019.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1008189,OO,-40.0,cifs/1008189.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1008775,NC(N)=O,134.0,cifs/1008775.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1008776,NC(N)=O,134.0,cifs/1008776.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11852,9014479,ClCl,-101.0,cifs/9014479.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11853,9015081,c1ccc2c(c1)Cc1ccccc1-2,116.0,cifs/9015081.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11854,9015108,Cl,-114.2,cifs/9015108.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11855,9015583,ClCl,-101.0,cifs/9015583.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11856,9016437,Cl,-114.2,cifs/9016437.cif,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
X_train = df_train.drop(columns=["id", "can_smiles", "T", "cif_path"])
y_train = df_train["T"].astype(float)

X_test = df_test.drop(columns=["id", "can_smiles", "T"])
y_test = df_test["T"].astype(float)

---
## Training Catboost:

In [12]:
import optuna
from catboost import CatBoostRegressor
from src.utils import eval_metrics

from sklearn.decomposition import PCA

import numpy as np

In [ ]:
# Objective function
def objective(trial):
    n_components = trial.suggest_int("pca_components", 2, X_train.shape[1])

    # Apply PCA
    pca = PCA(n_components=n_components)
    X_train_pca = pca.fit_transform(X_train)
    X_test_pca = pca.transform(X_test)

    params = {
        "iterations": trial.suggest_int("iterations", 200, 3000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "depth": trial.suggest_int("depth", 4, 14),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-2, 10.0, log=True),
        "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 1.0),
        "random_strength": trial.suggest_float("random_strength", 1e-3, 5.0, log=True),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "verbose": 0,
        "task_type": "CPU"
    }

    model = CatBoostRegressor(**params)
    model.fit(X_train_pca, y_train, eval_set=(X_test_pca, y_test), early_stopping_rounds=30)

    y_pred = model.predict(X_test_pca)
    return eval_metrics(y_test, y_pred, "regression")["R2"]

# Run Optuna
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=1000, n_jobs=32)

# Train final model with best params
best_params = study.best_params
best_params["loss_function"] = "RMSE"
best_params["verbose"] = 0

[I 2025-04-24 12:20:07,030] A new study created in memory with name: no-name-a447c853-7d6a-44f0-9206-6d63c6e95a1f

[I 2025-04-24 12:20:15,342] Trial 20 finished with value: 0.562616315857208 and parameters: {'pca_components': 44, 'iterations': 464, 'learning_rate': 0.1366570792851537, 'depth': 8, 'l2_leaf_reg': 0.10973588767995286, 'bagging_temperature': 0.33568844343585136, 'random_strength': 0.010407508933925108, 'border_count': 95}. Best is trial 20 with value: 0.562616315857208.
[I 2025-04-24 12:20:16,082] Trial 15 finished with value: 0.20266664827245928 and parameters: {'pca_components': 29, 'iterations': 332, 'learning_rate': 0.0028793059846204372, 'depth': 5, 'l2_leaf_reg': 0.023443525957596353, 'bagging_temperature': 0.35376842460149216, 'random_strength': 0.09406771195667414, 'border_count': 152}. Best is trial 20 with value: 0.562616315857208.
[I 2025-04-24 12:20:16,296] Trial 11 finished with value: 0.20869820951634188 and parameters: {'pca_components': 10, 'iterations': 293, 'learning_rate': 0.0025517322530007078, 'depth': 7, 'l2_leaf_reg': 1.6182082922891003, 'bagging_temperature': 0.8430532112730985, 'random_strength': 0.03557046757014227, 'border_count': 58}. Best is trial 20 with value: 0.562616315857208.
[I 2025-04-24 12:20:17,109] Trial 29 finished with value: 0.5702363646968465 and parameters: {'pca_components': 71, 'iterations': 883, 'learning_rate': 0.06103720208425497, 'depth': 4, 'l2_leaf_reg': 0.13855590920871802, 'bagging_temperature': 0.8905373386576828, 'random_strength': 0.00424325829021661, 'border_count': 148}. Best is trial 29 with value: 0.5702363646968465.
[I 2025-04-24 12:20:17,121] Trial 7 finished with value: 0.5518239662587203 and parameters: {'pca_components': 20, 'iterations': 239, 'learning_rate': 0.04615218763501141, 'depth': 7, 'l2_leaf_reg': 0.712769976778133, 'bagging_temperature': 0.7732671194809344, 'random_strength': 0.12128724521211855, 'border_count': 144}. Best is trial 29 with value: 0.5702363646968465.
[I 2025-04-24 12:20:17,310] Trial 4 finished with value: 0.5652444739360245 and parameters: {'pca_components': 59, 'iterations': 402, 'learning_rate': 0.05176900304780163, 'depth': 5, 'l2_leaf_reg': 9.120553533116471, 'bagging_temperature': 0.557523549961939, 'random_strength': 0.052903842393396946, 'border_count': 68}. Best is trial 29 with value: 0.5702363646968465.
[I 2025-04-24 12:20:17,823] Trial 25 finished with value: 0.5647882310620504 and parameters: {'pca_components': 12, 'iterations': 822, 'learning_rate': 0.1745847156090605, 'depth': 7, 'l2_leaf_reg': 2.145778020680106, 'bagging_temperature': 0.9449899122256793, 'random_strength': 0.001422123278132634, 'border_count': 137}. Best is trial 29 with value: 0.5702363646968465.
[I 2025-04-24 12:20:17,831] Trial 19 finished with value: 0.5559616595983556 and parameters: {'pca_components': 40, 'iterations': 973, 'learning_rate': 0.07641614367547976, 'depth': 6, 'l2_leaf_reg': 0.013167772762788906, 'bagging_temperature': 0.3760896014453834, 'random_strength': 0.904934847474822, 'border_count': 166}. Best is trial 29 with value: 0.5702363646968465.
[I 2025-04-24 12:20:17,840] Trial 31 finished with value: 0.1954442318638332 and parameters: {'pca_components': 63, 'iterations': 227, 'learning_rate': 0.0028291652441187203, 'depth': 7, 'l2_leaf_reg': 7.105543232102332, 'bagging_temperature': 0.23709065516330208, 'random_strength': 0.533836999430044, 'border_count': 158}. Best is trial 29 with value: 0.5702363646968465.
[I 2025-04-24 12:20:17,938] Trial 5 finished with value: 0.5695057885945696 and parameters: {'pca_components': 35, 'iterations': 912, 'learning_rate': 0.062384048456008714, 'depth': 4, 'l2_leaf_reg': 6.660475128405368, 'bagging_temperature': 0.9876328157040344, 'random_strength': 0.155500744779295, 'border_count': 202}. Best is trial 29 with value: 0.5702363646968465.
[I 2025-04-24 12:20:17,946] Trial 18 finished with value: 0.5795848754035495 and parameters: {'pca_components': 16, 'iterations': 286, 'learning_rate': 0.09069809705600307, 'depth': 8, 'l2_leaf_reg': 0.010981268147181969, 'bagging_temperature': 0.6876862885506051, 'random_strength': 0.008971419071255978, 'border_count': 167}. Best is trial 18 with value: 0.5795848754035495.
[I 2025-04-24 12:20:18,401] Trial 24 finished with value: 0.27976623171499115 and parameters: {'pca_components': 23, 'iterations': 679, 'learning_rate': 0.0035189953036432993, 'depth': 4, 'l2_leaf_reg': 5.4278633023561325, 'bagging_temperature': 0.521613055564303, 'random_strength': 0.3372440441131596, 'border_count': 65}. Best is trial 18 with value: 0.5795848754035495.
[I 2025-04-24 12:20:18,409] Trial 28 finished with value: 0.35650455446320606 and parameters: {'pca_components': 3, 'iterations': 376, 'learning_rate': 0.0950716185998607, 'depth': 8, 'l2_leaf_reg': 0.830332345332866, 'bagging_temperature': 0.2833267501192924, 'random_strength': 2.02826209214752, 'border_count': 79}. Best is trial 18 with value: 0.5795848754035495.
[I 2025-04-24 12:20:19,249] Trial 10 finished with value: 0.596644132310215 and parameters: {'pca_components': 41, 'iterations': 401, 'learning_rate': 0.16467783988479198, 'depth': 8, 'l2_leaf_reg': 5.735343125201546, 'bagging_temperature': 0.7326572547456116, 'random_strength': 0.0016188352045950663, 'border_count': 177}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:19,258] Trial 8 finished with value: 0.5640344631972275 and parameters: {'pca_components': 70, 'iterations': 795, 'learning_rate': 0.028356319865698126, 'depth': 5, 'l2_leaf_reg': 0.9278423119291389, 'bagging_temperature': 0.7487657785590499, 'random_strength': 0.5085375491489468, 'border_count': 93}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:19,262] Trial 6 finished with value: 0.49782007247310556 and parameters: {'pca_components': 43, 'iterations': 660, 'learning_rate': 0.011134177605146617, 'depth': 6, 'l2_leaf_reg': 9.652907682521109, 'bagging_temperature': 0.6334989393381155, 'random_strength': 0.011567946490651739, 'border_count': 38}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:19,267] Trial 27 finished with value: 0.4996847026908542 and parameters: {'pca_components': 65, 'iterations': 482, 'learning_rate': 0.010350759452145277, 'depth': 6, 'l2_leaf_reg': 0.09454911342138626, 'bagging_temperature': 0.8944569741912836, 'random_strength': 0.009342070890912983, 'border_count': 191}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:19,273] Trial 0 finished with value: 0.26774475820610233 and parameters: {'pca_components': 65, 'iterations': 476, 'learning_rate': 0.0018027805749692867, 'depth': 7, 'l2_leaf_reg': 0.02601396422367141, 'bagging_temperature': 0.8562930305058845, 'random_strength': 0.0035100163143060867, 'border_count': 36}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:19,278] Trial 21 finished with value: 0.5124230095429742 and parameters: {'pca_components': 66, 'iterations': 302, 'learning_rate': 0.01270313213031331, 'depth': 8, 'l2_leaf_reg': 2.5463383205211274, 'bagging_temperature': 0.5756364200709111, 'random_strength': 0.07813485686895565, 'border_count': 126}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:19,323] Trial 17 finished with value: 0.35262741367122075 and parameters: {'pca_components': 4, 'iterations': 635, 'learning_rate': 0.01736185756457511, 'depth': 7, 'l2_leaf_reg': 0.29392686071969376, 'bagging_temperature': 0.4231437165738715, 'random_strength': 0.8597531430254929, 'border_count': 69}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:19,720] Trial 23 finished with value: 0.4568551499110284 and parameters: {'pca_components': 65, 'iterations': 692, 'learning_rate': 0.00513370658832853, 'depth': 7, 'l2_leaf_reg': 2.736770558288479, 'bagging_temperature': 0.3148639152182908, 'random_strength': 0.8075878198968625, 'border_count': 77}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:20,032] Trial 14 finished with value: 0.3247491478611093 and parameters: {'pca_components': 49, 'iterations': 419, 'learning_rate': 0.0035331181195355217, 'depth': 8, 'l2_leaf_reg': 0.621412658060287, 'bagging_temperature': 0.5891141857580638, 'random_strength': 2.749603315000184, 'border_count': 215}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:20,310] Trial 2 finished with value: 0.3407305730543202 and parameters: {'pca_components': 23, 'iterations': 969, 'learning_rate': 0.0017763803058098396, 'depth': 7, 'l2_leaf_reg': 0.045431033797911136, 'bagging_temperature': 0.41834658403483327, 'random_strength': 0.4405295560651021, 'border_count': 179}. Best is trial 10 with value: 0.596644132310215.
[I 2025-04-24 12:20:20,993] Trial 22 finished with value: 0.5306603533400844 and parameters: {'pca_components': 63, 'iterations': 897, 'learning_rate': 0.008924806440900105, 'depth': 7, 'l2_leaf_reg': 9.510607968667394, 'bagging_temperature': 0.7574450309615303, 'random_strength': 0.3701982944164868, 'border_count': 211}. Best is trial 10 with value: 0.596644132310215.

In [ ]:
final_model = CatBoostRegressor(**best_params)
final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)
print(eval_metrics(y_test, y_pred))