In [41]:
import os
import rootutils

from tqdm.notebook import tqdm

rootutils.setup_root(os.path.abspath('./'), indicator=".project-root", pythonpath=True, dotenv=True, cwd=True)

# auto-loading of imports from outside scripts
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [42]:
import pandas as pd
import re

In [43]:
df_coord_numbs = pd.read_csv("data_cod/coord_numbs.csv")
df_coord_numbs.rename(columns={"smiles": "can_smiles"}, inplace=True)

In [44]:
# your allowed elements
organic = {"C", "H", "O", "N", "S", "F", "Cl", "Br", "P"}

# regex to pull out element symbols (Cl, Br or any capital letter + optional lowercase)
_pattern = re.compile(r'Cl|Br|[A-Z][a-z]?')

def smiles_only_organic(smiles: str) -> bool:
    """Return True if every element token in a SMILES string is in our organic set."""
    tokens = _pattern.findall(smiles)
    return all(tok in organic for tok in tokens)

def col_name_ok(col: str) -> bool:
    """
    Return True if, when splitting the column name on dash/–,
    every part is one of our organic elements.
    """
    parts = re.split(r'[–-]', col)
    return all(part in organic for part in parts)

# 1) Filter rows by can_smiles
df_rows = df_coord_numbs[df_coord_numbs['can_smiles'].apply(smiles_only_organic)]

# 2) Build list of columns to keep (and also keep can_smiles itself)
keep_cols = ['id', 'can_smiles'] + [c for c in df_rows.columns if col_name_ok(c)]

# 3) Slice down to just those columns
df_coord_numbs = df_rows[keep_cols]

#### Leave only organic crystalls:
`C, H, O, N, S, F, Cl, Br, P`

In [45]:
organic_elements = ["C", "H", "O", "N", "S", "F", "Cl", "Br", "P"]

---
## Merging with temperatures:

In [46]:
# Drop rows and columns that contain only zeros:

rows_only_zeros = df_coord_numbs[(df_coord_numbs == 0).all(axis=1)]
columns_only_zeros = df_coord_numbs.loc[:, (df_coord_numbs == 0).all(axis=0)]

df_coord_numbs = df_coord_numbs.drop(columns=columns_only_zeros.columns, index=rows_only_zeros.index)

In [47]:
df_merged_temp = pd.read_csv("data_cod/cod_bradley_merged.csv")
df_merged_temp = df_merged_temp[df_merged_temp["id"].isin(df_coord_numbs["id"])]

# Only bradley, to use part of it for test:
df_bradley_temp = pd.read_csv("data_cod/bradley_with_cif.csv")
df_bradley_temp = df_bradley_temp[df_bradley_temp["id"].isin(df_coord_numbs["id"])]

---
## Creating Train and Test splits:
- 0.2 of Bradley is test, rest is train

In [48]:
TEST_BRADLEY_FRAC = 0.2

In [49]:
df_test = df_bradley_temp.sample(frac=TEST_BRADLEY_FRAC, random_state=42)

df_train = df_merged_temp.drop(index=df_merged_temp[df_merged_temp["id"].isin(df_test["id"])].index)

In [50]:
df_train = pd.merge(df_train, df_coord_numbs, on=["id", "can_smiles"], how="inner")
df_test = pd.merge(df_test, df_coord_numbs, on=["id", "can_smiles"], how="inner")

In [51]:
X_train = df_train.drop(columns=["id", "can_smiles", "T", "cif_path"])
y_train = df_train["T"].astype(float)

X_test = df_test.drop(columns=["id", "can_smiles", "T"])
y_test = df_test["T"].astype(float)

In [78]:
X_test

,Br–Br,C–Br,Br–C,C–C,C–Cl,Cl–C,C–H,H–C,C–N,N–C,...,H–O,O–O,P–H,H–P,P–P,S–H,H–S,S–O,O–S,S–S
0,0.0,0.00,0.0,0.706,0.0,0.0,0.941,0.703,1.294,2.000,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
1,0.0,0.00,0.0,1.548,0.0,0.0,0.720,0.730,0.548,1.750,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
2,0.0,0.00,0.0,2.526,0.0,0.0,0.519,1.000,0.000,0.000,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
3,0.0,0.00,0.0,1.308,0.0,0.0,0.619,0.610,0.615,1.000,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
4,0.0,0.00,0.0,1.703,0.0,0.0,1.135,0.869,0.236,1.429,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.647,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,0.0,0.50,1.0,1.500,0.0,0.0,1.000,1.000,0.000,0.000,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
390,0.0,0.00,0.0,1.351,0.0,0.0,1.262,0.626,0.237,2.000,...,0.295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
391,0.0,0.15,1.0,2.000,0.0,0.0,0.708,1.000,0.146,3.000,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
392,1.0,0.00,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.000,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0
393,0.0,0.00,0.0,1.450,0.0,0.0,1.200,0.600,0.000,0.000,...,0.464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0

In [77]:
X_train

,Br–Br,C–Br,Br–C,C–C,C–Cl,Cl–C,C–H,H–C,C–N,N–C,...,H–O,O–O,P–H,H–P,P–P,S–H,H–S,S–O,O–S,S–S
0,0.0,0.0,0.0,2.324,0.0,0.0,1.347,0.876,0.000,0.0,...,0.140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.876,0.0,0.0,0.920,0.957,0.153,3.0,...,0.039,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,...,1.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,2.000,1.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,2.000,1.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5188,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5189,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5190,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5191,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5192,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

---
## Training Catboost:

In [52]:
import optuna
from catboost import CatBoostRegressor
from src.utils import eval_metrics

from sklearn.decomposition import PCA

import numpy as np

In [70]:
# Objective function
def objective(trial):

    params = {
        "iterations": trial.suggest_int("iterations", 300, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "depth": trial.suggest_int("depth", 4, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-2, 10.0, log=True),
        "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 1.0),
        "random_strength": trial.suggest_float("random_strength", 1e-3, 5.0, log=True),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "verbose": 0,
        "task_type": "CPU"
    }

    model = CatBoostRegressor(**params)
    model.fit(X_train, y_train, eval_set=(X_test, y_test), early_stopping_rounds=30)

    y_pred = model.predict(X_test)
    return eval_metrics(y_test, y_pred, "regression")["R2"]

# Run Optuna
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50, n_jobs=8)

# Train final model with best params
best_params = study.best_params
best_params["loss_function"] = "RMSE"
best_params["verbose"] = 0

[I 2025-04-24 22:04:15,433] A new study created in memory with name: no-name-d5d01a5e-e0a9-4a3f-bafa-b667655cc443

[I 2025-04-24 22:04:16,051] Trial 6 finished with value: 0.6766817044445199 and parameters: {'iterations': 526, 'learning_rate': 0.14856894962143957, 'depth': 6, 'l2_leaf_reg': 0.4211680617292804, 'bagging_temperature': 0.9614181566658634, 'random_strength': 1.9332014366678725, 'border_count': 230}. Best is trial 6 with value: 0.6766817044445199.
[I 2025-04-24 22:04:16,411] Trial 5 finished with value: 0.506341422189867 and parameters: {'iterations': 356, 'learning_rate': 0.005852835193889274, 'depth': 5, 'l2_leaf_reg': 0.010547863703789448, 'bagging_temperature': 0.24771133996265526, 'random_strength': 0.00508425155675731, 'border_count': 152}. Best is trial 6 with value: 0.6766817044445199.
[I 2025-04-24 22:04:16,588] Trial 3 finished with value: 0.6767740208629572 and parameters: {'iterations': 880, 'learning_rate': 0.11477098765106826, 'depth': 8, 'l2_leaf_reg': 0.5920993265565944, 'bagging_temperature': 0.1986637711862137, 'random_strength': 0.17053747411420384, 'border_count': 146}. Best is trial 3 with value: 0.6767740208629572.
[I 2025-04-24 22:04:17,336] Trial 4 finished with value: 0.4334929314500434 and parameters: {'iterations': 841, 'learning_rate': 0.0016768780355139738, 'depth': 5, 'l2_leaf_reg': 0.15477592901794623, 'bagging_temperature': 0.6264763917463012, 'random_strength': 0.003293098302457636, 'border_count': 248}. Best is trial 3 with value: 0.6767740208629572.
[I 2025-04-24 22:04:17,748] Trial 9 finished with value: 0.6681701096762804 and parameters: {'iterations': 668, 'learning_rate': 0.0586126622955561, 'depth': 5, 'l2_leaf_reg': 0.02356285485795866, 'bagging_temperature': 0.24870156116308695, 'random_strength': 0.04878169675346321, 'border_count': 131}. Best is trial 3 with value: 0.6767740208629572.
[I 2025-04-24 22:04:17,787] Trial 7 finished with value: 0.597622158483575 and parameters: {'iterations': 514, 'learning_rate': 0.005201314071673192, 'depth': 8, 'l2_leaf_reg': 0.0677301243066369, 'bagging_temperature': 0.8444468045943594, 'random_strength': 0.6358777457314241, 'border_count': 157}. Best is trial 3 with value: 0.6767740208629572.
[I 2025-04-24 22:04:18,515] Trial 8 finished with value: 0.6843289194061624 and parameters: {'iterations': 412, 'learning_rate': 0.07865838849599145, 'depth': 10, 'l2_leaf_reg': 0.028398224366794723, 'bagging_temperature': 0.9975048439508355, 'random_strength': 0.28733166014980366, 'border_count': 103}. Best is trial 8 with value: 0.6843289194061624.
[I 2025-04-24 22:04:18,637] Trial 10 finished with value: 0.6475045740821609 and parameters: {'iterations': 917, 'learning_rate': 0.011579089345925055, 'depth': 6, 'l2_leaf_reg': 0.08435584827193797, 'bagging_temperature': 0.02926367445598055, 'random_strength': 0.026488357803986964, 'border_count': 63}. Best is trial 8 with value: 0.6843289194061624.
[I 2025-04-24 22:04:19,646] Trial 12 finished with value: 0.5973176148892635 and parameters: {'iterations': 655, 'learning_rate': 0.005500922755498792, 'depth': 6, 'l2_leaf_reg': 0.5563783382222635, 'bagging_temperature': 0.7285803683659784, 'random_strength': 0.023831579556607484, 'border_count': 121}. Best is trial 8 with value: 0.6843289194061624.
[I 2025-04-24 22:04:19,959] Trial 1 finished with value: 0.7018459463990985 and parameters: {'iterations': 559, 'learning_rate': 0.039693088247241146, 'depth': 10, 'l2_leaf_reg': 0.13535394175278478, 'bagging_temperature': 0.25460317760251217, 'random_strength': 0.007600858401536693, 'border_count': 196}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:20,136] Trial 2 finished with value: 0.6888470733514094 and parameters: {'iterations': 968, 'learning_rate': 0.011504060569506654, 'depth': 9, 'l2_leaf_reg': 0.059362453502645324, 'bagging_temperature': 0.5254874961761848, 'random_strength': 0.503995269127782, 'border_count': 86}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:20,370] Trial 0 finished with value: 0.6866187539176649 and parameters: {'iterations': 761, 'learning_rate': 0.010195406558285939, 'depth': 9, 'l2_leaf_reg': 0.08423208903536425, 'bagging_temperature': 0.786767495083179, 'random_strength': 0.09885258866016972, 'border_count': 186}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:20,414] Trial 14 finished with value: 0.6613528290770918 and parameters: {'iterations': 577, 'learning_rate': 0.029005484434410297, 'depth': 6, 'l2_leaf_reg': 2.664137297181712, 'bagging_temperature': 0.7448313058926584, 'random_strength': 0.010063947378544841, 'border_count': 177}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:20,451] Trial 15 finished with value: 0.6864199169962681 and parameters: {'iterations': 776, 'learning_rate': 0.06202607344657847, 'depth': 8, 'l2_leaf_reg': 2.2521223771752674, 'bagging_temperature': 0.05395634110588854, 'random_strength': 0.02188636874930631, 'border_count': 238}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:21,582] Trial 13 finished with value: 0.6919264889942593 and parameters: {'iterations': 930, 'learning_rate': 0.025857373034620393, 'depth': 8, 'l2_leaf_reg': 0.02291452680322595, 'bagging_temperature': 0.513121888324076, 'random_strength': 3.1152961848603016, 'border_count': 156}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:21,693] Trial 17 finished with value: 0.6965542176529489 and parameters: {'iterations': 742, 'learning_rate': 0.29542775025326795, 'depth': 10, 'l2_leaf_reg': 5.400852698544905, 'bagging_temperature': 0.46147239399487405, 'random_strength': 0.001304755156449812, 'border_count': 204}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:22,523] Trial 11 finished with value: 0.6861394912368022 and parameters: {'iterations': 901, 'learning_rate': 0.009594136306173912, 'depth': 9, 'l2_leaf_reg': 0.052052961621497675, 'bagging_temperature': 0.6522020454201294, 'random_strength': 0.06612350259563307, 'border_count': 84}. Best is trial 1 with value: 0.7018459463990985.
[I 2025-04-24 22:04:23,521] Trial 23 finished with value: 0.7039895797185849 and parameters: {'iterations': 757, 'learning_rate': 0.24653007391129356, 'depth': 10, 'l2_leaf_reg': 7.855171896754749, 'bagging_temperature': 0.45824543513621746, 'random_strength': 0.001100570948883273, 'border_count': 206}. Best is trial 23 with value: 0.7039895797185849.
[I 2025-04-24 22:04:24,171] Trial 19 finished with value: 0.6904734273738904 and parameters: {'iterations': 993, 'learning_rate': 0.04423471254318685, 'depth': 10, 'l2_leaf_reg': 2.7869763322741257, 'bagging_temperature': 0.4685991052432803, 'random_strength': 0.0010851453128026514, 'border_count': 71}. Best is trial 23 with value: 0.7039895797185849.
[I 2025-04-24 22:04:24,568] Trial 26 finished with value: 0.6156319447148009 and parameters: {'iterations': 592, 'learning_rate': 0.1935353110001418, 'depth': 4, 'l2_leaf_reg': 9.99520730759702, 'bagging_temperature': 0.13069574503363107, 'random_strength': 0.004235070472475849, 'border_count': 37}. Best is trial 23 with value: 0.7039895797185849.
[I 2025-04-24 22:04:25,026] Trial 24 finished with value: 0.7173846675347466 and parameters: {'iterations': 749, 'learning_rate': 0.28552322538792685, 'depth': 10, 'l2_leaf_reg': 9.429564271530817, 'bagging_temperature': 0.40190384867885803, 'random_strength': 0.0011998758122901975, 'border_count': 199}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:25,775] Trial 25 finished with value: 0.7062594767324456 and parameters: {'iterations': 441, 'learning_rate': 0.2824937453589799, 'depth': 10, 'l2_leaf_reg': 9.643160817513621, 'bagging_temperature': 0.37457519699619335, 'random_strength': 0.0011310466821849697, 'border_count': 213}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:26,685] Trial 20 finished with value: 0.6866346944626406 and parameters: {'iterations': 806, 'learning_rate': 0.0291453315228322, 'depth': 10, 'l2_leaf_reg': 2.613296709774803, 'bagging_temperature': 0.4553533844515911, 'random_strength': 2.9839177076601686, 'border_count': 41}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:26,853] Trial 21 finished with value: 0.7056675553269338 and parameters: {'iterations': 988, 'learning_rate': 0.027023486655379785, 'depth': 10, 'l2_leaf_reg': 0.23157761549393402, 'bagging_temperature': 0.44277007157719683, 'random_strength': 0.0012645637915953143, 'border_count': 54}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:26,912] Trial 16 finished with value: 0.7028877149470381 and parameters: {'iterations': 690, 'learning_rate': 0.02435710275406351, 'depth': 10, 'l2_leaf_reg': 0.14550402207662472, 'bagging_temperature': 0.7715036701949453, 'random_strength': 0.38745923046566116, 'border_count': 152}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:26,937] Trial 29 finished with value: 0.6889370492068165 and parameters: {'iterations': 444, 'learning_rate': 0.259985070072469, 'depth': 9, 'l2_leaf_reg': 8.527188638736664, 'bagging_temperature': 0.36282596988073523, 'random_strength': 0.002100048295047887, 'border_count': 220}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:26,965] Trial 28 finished with value: 0.7000480354962818 and parameters: {'iterations': 703, 'learning_rate': 0.2740526519737353, 'depth': 10, 'l2_leaf_reg': 1.420371611977348, 'bagging_temperature': 0.3412400030106031, 'random_strength': 0.0018256914119637862, 'border_count': 217}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:28,091] Trial 30 finished with value: 0.6901936468202379 and parameters: {'iterations': 706, 'learning_rate': 0.2518409189446193, 'depth': 9, 'l2_leaf_reg': 9.936281493391103, 'bagging_temperature': 0.3557571784880575, 'random_strength': 0.001954121359373688, 'border_count': 221}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:28,453] Trial 27 finished with value: 0.44800680165831896 and parameters: {'iterations': 458, 'learning_rate': 0.0020483805642537256, 'depth': 9, 'l2_leaf_reg': 1.0672204320623853, 'bagging_temperature': 0.3761008454879714, 'random_strength': 0.0020010043415095717, 'border_count': 209}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:28,531] Trial 34 finished with value: 0.696190423676011 and parameters: {'iterations': 333, 'learning_rate': 0.11967771899700193, 'depth': 9, 'l2_leaf_reg': 1.397694790804453, 'bagging_temperature': 0.3810755293305687, 'random_strength': 0.002595255547326552, 'border_count': 183}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:28,585] Trial 33 finished with value: 0.6900447344256371 and parameters: {'iterations': 324, 'learning_rate': 0.10689766019620198, 'depth': 9, 'l2_leaf_reg': 1.012067950666764, 'bagging_temperature': 0.36045114917801496, 'random_strength': 0.0024615667915370656, 'border_count': 173}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:28,891] Trial 22 finished with value: 0.6705627447769118 and parameters: {'iterations': 452, 'learning_rate': 0.02620156994281306, 'depth': 10, 'l2_leaf_reg': 0.21041285025821982, 'bagging_temperature': 0.43200942455078045, 'random_strength': 4.603050777746175, 'border_count': 211}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:29,213] Trial 31 finished with value: 0.7112857782862936 and parameters: {'iterations': 462, 'learning_rate': 0.1071050439786041, 'depth': 9, 'l2_leaf_reg': 0.9208285688170492, 'bagging_temperature': 0.3632111340834617, 'random_strength': 0.0023449957306187403, 'border_count': 211}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:29,466] Trial 36 finished with value: 0.6788752067534167 and parameters: {'iterations': 316, 'learning_rate': 0.10174995825583255, 'depth': 7, 'l2_leaf_reg': 4.787908269405131, 'bagging_temperature': 0.6005411025122965, 'random_strength': 0.013826353120971465, 'border_count': 178}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:29,890] Trial 35 finished with value: 0.7022779338251537 and parameters: {'iterations': 369, 'learning_rate': 0.12552952953909977, 'depth': 9, 'l2_leaf_reg': 1.043920652932179, 'bagging_temperature': 0.5839490654865181, 'random_strength': 0.011558332053110361, 'border_count': 169}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:29,953] Trial 39 finished with value: 0.6836224437891525 and parameters: {'iterations': 617, 'learning_rate': 0.1761867467648616, 'depth': 7, 'l2_leaf_reg': 5.227798786710566, 'bagging_temperature': 0.5695415635983361, 'random_strength': 0.008354360263295196, 'border_count': 195}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:29,998] Trial 40 finished with value: 0.6760833050627306 and parameters: {'iterations': 372, 'learning_rate': 0.1704348494364314, 'depth': 7, 'l2_leaf_reg': 5.128071834862822, 'bagging_temperature': 0.5562975247546215, 'random_strength': 0.00973787147444715, 'border_count': 255}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:30,309] Trial 41 finished with value: 0.6822884460277492 and parameters: {'iterations': 384, 'learning_rate': 0.18256735891894715, 'depth': 9, 'l2_leaf_reg': 0.30359523358356044, 'bagging_temperature': 0.5571605118073728, 'random_strength': 0.0073112935321859255, 'border_count': 255}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:30,682] Trial 42 finished with value: 0.6712028588449345 and parameters: {'iterations': 611, 'learning_rate': 0.16837763720003734, 'depth': 8, 'l2_leaf_reg': 0.2382167640696266, 'bagging_temperature': 0.30037713025431567, 'random_strength': 0.005657665617211435, 'border_count': 248}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:30,765] Trial 32 finished with value: 0.30042496107309846 and parameters: {'iterations': 442, 'learning_rate': 0.0010715896696131318, 'depth': 9, 'l2_leaf_reg': 1.099638454744429, 'bagging_temperature': 0.36944587934140116, 'random_strength': 0.002496147890558135, 'border_count': 216}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:31,229] Trial 38 finished with value: 0.6899302549060773 and parameters: {'iterations': 615, 'learning_rate': 0.19943404096836093, 'depth': 10, 'l2_leaf_reg': 4.989948935970198, 'bagging_temperature': 0.5778315964800299, 'random_strength': 0.001136490411781327, 'border_count': 196}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:31,620] Trial 18 finished with value: 0.6982796848098982 and parameters: {'iterations': 759, 'learning_rate': 0.025383298755355457, 'depth': 10, 'l2_leaf_reg': 3.8354992007361752, 'bagging_temperature': 0.44114539364172656, 'random_strength': 0.001601765571181952, 'border_count': 201}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:32,137] Trial 43 finished with value: 0.691843872737737 and parameters: {'iterations': 510, 'learning_rate': 0.1778981927022954, 'depth': 10, 'l2_leaf_reg': 0.21168219300781588, 'bagging_temperature': 0.27764717617721957, 'random_strength': 0.006394848483961125, 'border_count': 191}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:32,356] Trial 37 finished with value: 0.5611549686546272 and parameters: {'iterations': 839, 'learning_rate': 0.0027467397287099433, 'depth': 7, 'l2_leaf_reg': 5.143535854344253, 'bagging_temperature': 0.580583236592134, 'random_strength': 0.012434438157774591, 'border_count': 169}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:33,205] Trial 44 finished with value: 0.7030529334683215 and parameters: {'iterations': 502, 'learning_rate': 0.07984353705839545, 'depth': 10, 'l2_leaf_reg': 0.2922569039307408, 'bagging_temperature': 0.2998041771231486, 'random_strength': 0.006150027910758166, 'border_count': 191}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:33,615] Trial 45 finished with value: 0.6945205720713156 and parameters: {'iterations': 539, 'learning_rate': 0.07769620377825825, 'depth': 10, 'l2_leaf_reg': 0.3237659718067573, 'bagging_temperature': 0.3027485273518399, 'random_strength': 0.004719658636004385, 'border_count': 192}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:33,962] Trial 46 finished with value: 0.6975292902375162 and parameters: {'iterations': 517, 'learning_rate': 0.07171417139664095, 'depth': 10, 'l2_leaf_reg': 0.49995907699585346, 'bagging_temperature': 0.20625032239176988, 'random_strength': 0.003699090958150971, 'border_count': 234}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:34,240] Trial 47 finished with value: 0.7082001288582866 and parameters: {'iterations': 517, 'learning_rate': 0.0792920322828685, 'depth': 10, 'l2_leaf_reg': 0.468684404289239, 'bagging_temperature': 0.14007670963545904, 'random_strength': 0.0037743761343730533, 'border_count': 191}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:35,065] Trial 49 finished with value: 0.6957662303633256 and parameters: {'iterations': 848, 'learning_rate': 0.08548269474590564, 'depth': 10, 'l2_leaf_reg': 7.053775614810108, 'bagging_temperature': 0.20550313004462797, 'random_strength': 0.0034548081262798552, 'border_count': 233}. Best is trial 24 with value: 0.7173846675347466.
[I 2025-04-24 22:04:35,211] Trial 48 finished with value: 0.6953763091832812 and parameters: {'iterations': 510, 'learning_rate': 0.08021619033391134, 'depth': 10, 'l2_leaf_reg': 3.827675165099441, 'bagging_temperature': 0.18928062104984522, 'random_strength': 0.001401861828838089, 'border_count': 233}. Best is trial 24 with value: 0.7173846675347466.

In [75]:
best_params["iterations"] = 1000

In [76]:
final_model = CatBoostRegressor(**best_params)
final_model.fit(X_train, y_train, verbose=100)

y_pred = final_model.predict(X_test)
eval_metrics(y_test, y_pred, "regression")

0:	learn: 105.8127004	total: 12.8ms	remaining: 12.8s
100:	learn: 67.2635775	total: 900ms	remaining: 8.01s
200:	learn: 54.7505090	total: 1.71s	remaining: 6.8s
300:	learn: 45.9682266	total: 2.54s	remaining: 5.91s
400:	learn: 40.9813115	total: 3.43s	remaining: 5.12s
500:	learn: 35.4721391	total: 4.25s	remaining: 4.23s
600:	learn: 30.9378458	total: 5.07s	remaining: 3.36s
700:	learn: 27.7884738	total: 5.87s	remaining: 2.5s
800:	learn: 24.8699834	total: 6.68s	remaining: 1.66s
900:	learn: 22.6651007	total: 7.49s	remaining: 823ms
999:	learn: 20.7780652	total: 8.29s	remaining: 0us

{'MSE': 2988.978920531826,
 'RMSE': 54.671554948911286,
 'MAE': 35.228787711968074,
 'R2': 0.6888648958572654}